version: '3.9'
name: voors-pizza
services:
  postgres:
    container_name: voorspizza_postgres_container
    image: postgres
    restart: always
    ports:
      - '5433:5433'
    volumes:
      - './docker-volumes/postgres:/var/lib/postgresql'
    environment:
      POSTGRES_USER: voorspizza
      POSTGRES_PASSWORD: voorspizza
    command: -p 5433
  api:
    container_name: voorspizza_api_container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3001:3001
    env_file: ./.env
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://voorspizza:voorspizza@localhost:5433/voorspizza
    volumes:
      - ./docker-volumes/voorspizza_api_container/src:/app/src
    depends_on:
      - postgres
