export const FIND_PERSONALIZATIONS_FACTORY = 'FIND_PERSONALIZATIONS_FACTORY';

export const FIND_FLAVOURS_FACTORY = 'FIND_FLAVOURS_FACTORY';

export const FIND_SIZES_FACTORY = 'FIND_SIZES_FACTORY';

export const CREATE_ORDER_FACTORY = 'CREATE_ORDER_FACTORY';
export const FIND_ORDER_BY_ID_FACTORY = 'FIND_ORDER_BY_ID_FACTORY';
